allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': false
  '@prisma/engines': false
  better-sqlite3: true
  esbuild: true
  prisma: false
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
